botChannels:
  #To restrict which voice channels the bot can use, set below to true.
  restrictVoiceChannels: False
  #If above is set to true, list allowed channel/s IDs in a list as shown below.
  allowedVoiceChannels: [123456789012345678, 987654321098765432]
  
  #To restrict which test channels the bot can receive commands on, set below to true.
  restrictTextChannels: False
  #If above is set to true, list allowed channel/s IDs in a list as shown below.
  allowedTextChannels: [112233445566778899, 998877665544332211]
  
  #If you want the bot to log, login and error info in a channel, set below to True
  enableLogChannel: True
  #If above is set to true, list your logging channel ID below
  logChannel: 246813579024681357

private:
  #Discord bot token
  discordBotToken: F4K3T0K3N_ikb331nmGsvgHPGAv8jwFV3gKFs9eR.nF4lgje68ZdrEX9aSJ
  
  #Rainwave API ID
  rainwaveID: 12345
  
  #Rainwave API Key
  rainwaveKey: 12345abcde
    
dependencies:
  #Location of FFMPEG file.
  ffmpegLocation: "/usr/bin/ffmpeg"
  
  #Location of opus file.
  opusLocation: "/usr/lib/libopus.so.0"

options:
  #Change the name of your bot here
  botName: "Rain.Wave"

  #Change the prefix of your bot here
  botPrefix: "rw."

  #Enables display of song progress in a numerical style timer e.g. [01:05/01:21]
  enableProgressTimes: True
  
  #Enables display of song progress in a graphical manner e.g. ▰▰▰▱▱▱▱▱▱▱▱
  enableProgressBar: True
  
  #Allows selection of progress bar style between 1 and 2
  #1 is a left to right "fill" style progress bar e.g. ▰▰▰▱▱▱▱▱▱▱▱
  #2 is a moving indicator style progress bar e.g. ▱▱▱▰▱▱▱▱▱▱▱
  progressBarStyle: 1
  
  #Allows selection of progress bar character length
  progressBarLength: 14
  
  #Allows selection of characters which make up the progress bar
  #for style 1 ['▰','▱'] or ['▶','▷'] or ['█','░'] is suggested
  #for style 2 ['═','╪'] or ['—','⎔'] or ['▬',':radio_button:'] is suggested
  progressBarCharacters: ['▰','▱']

  #Allows selection of embed sidebar color as an (r, g, b) value.  
  #You can use https://it-tools.tech/color-converter to generate an rgb color value
  embedColor: [24, 135, 210]
  
  #Numer of seconds between refresh of progress bar and timer, can be increased if user is being rate limited.
  #Minimum value can never be below 6.
  refreshDelay: 6
  
  #If set to `True`, bot will disconnect if no users are present in the bots voice channel.
  autoDisconnect: True

  #Logging level, can be set to DEBUG, INFO, WARNING, ERROR, CRITICAL.  If INFO provides too much info, switch to WARNING
  logLevel: "INFO"